# Generated by Django 3.2.6 on 2022-12-18 15:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_photo_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='people_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
